# ----------------------------
# group nb 108
# noma1 : 68171400 Laritza Cabrera Alba
# noma2 : name2 Magali Legast
# ----------------------------

# TODO complete the header with your group number, your noma's and full names

# TODO write your makefile here
all :compile run

compile :
	@ozc -c *.oz

run :
	@ozengine Main.ozf

clean :
	@rm -rf GUI.ozf Input.ozf Main.ozf PlayerManager.ozf
